title: 糸の窝
subtitle: '大废物'
description: '一个大废物的博客'
keywords: 
  - "Yuameshi"
  - "糸"
  - "博客"
  - "Blog"
author: 糸
language: zh-CN
timezone: ''

url: https://www.yuameshi.top/
permalink: :year/:month/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true 
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: true
  # tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  # tab_replace: ''

index_generator:
  path: ''
  per_page: 10
  order_by: -date

default_category: Uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

theme: mdx

deploy:
  type: git
  repository: git@github.com:Yuameshi/MyBlog.git
  branch: gh-pages

feed:
  enable: true
  type: rss2
  path: rss.xml
  limit: 0
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: /pwa.png
  autodiscovery: true

search:
  path: search.json
  field: post
  content: true

all_minifier: true

js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false

html_minifier:
  enable: true
  ignore_error: false
  silent: false
  exclude:

css_minifier:
  enable: true
  silent: false
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  silent: false
  # output:
  # compress:
  exclude: 
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 3
  pngquant: false
  progressive: false
  silent: false
